const T = {
  fr: {
    navDemo: 'Réserver une démo',
    navLogin: 'Connexion',
    heroBadge: '🇹🇳 Conçu pour la Tunisie',
    heroTitle: 'GÉREZ\nVOTRE SALLE.\nSIMPLEMENT.',
    heroSub: 'Fini les tableaux Excel et les groupes WhatsApp. Trainw connecte vos coachs, vos clients et votre planning en un seul endroit.',
    heroDemo: 'Réserver une démo gratuite',
    heroLogin: 'Connexion',
    heroNote: 'Essai gratuit 30 jours · Aucune carte bancaire requise',
    hvSessions: "Séances aujourd'hui",
    hvRevenue: 'Revenus',
    hvClients: 'Clients Actifs',
    hvDemoLabel: 'Données d\'exemple',
    stat1: 'Accès Réservation',
    stat2: 'Rôles en Un · Salle · Coach · Client',
    stat3: 'Tunisie',
    whoTag: 'Pour qui',
    whoTitle: 'Conçu pour Toute la Salle',
    gymTitle: 'Propriétaires de Salles',
    gymDesc: 'Gérez toute votre activité depuis un seul tableau de bord. Coachs, revenus, clients — tout centralisé.',
    gymB1: 'Réservations et revenus en temps réel',
    gymB2: 'Suivi des performances des coachs',
    gymB3: 'Planification des séances et classes',
    gymB4: 'Gestion complète des membres',
    coachTitle: 'Coachs',
    coachDesc: "Concentrez-vous sur l'entraînement, pas l'administratif. Planning, clients et revenus en un seul endroit.",
    coachB1: 'Planning et revenus centralisés',
    coachB2: 'Suivi des progrès clients',
    coachB3: 'Générateur de notes de séance',
    coachB4: 'Avis clients vérifiés',
    clientTitle: 'Clients',
    clientDesc: 'Réservez vos séances, suivez vos progrès et restez connecté à votre coach — tout en un.',
    clientB1: 'Réservation de séances à tout moment',
    clientB2: 'Suivi des mensurations et du poids',
    clientB3: 'Guide nutrition personnalisé',
    clientB4: 'Contact direct avec le coach',
    whoCta: 'Commencer →',
    howTag: 'Comment ça marche',
    howTitle: 'Opérationnel en 3 Étapes',
    how1Title: 'Créez votre salle',
    how1Desc: 'Inscription en 2 minutes. Ajoutez le nom de votre salle, vos informations, et vous êtes prêt.',
    how2Title: 'Ajoutez vos coachs et clients',
    how2Desc: 'Invitez vos coachs, enregistrez vos membres. Chacun accède à son propre tableau de bord.',
    how3Title: 'Gérez tout depuis un endroit',
    how3Desc: 'Planning, réservations, suivi clients, revenus — tout centralisé. Fini le chaos WhatsApp.',
    pricingTag: 'Tarifs',
    pricingTitle: 'Simple et Transparent',
    pFreeTag: 'Essai Gratuit',
    pFreeName: 'Démarrage',
    pFreePeriod: '30 jours gratuits',
    pFF1: "Jusqu'à 50 clients",
    pFF2: 'Planification de base',
    pFF3: 'Messagerie clients',
    pFF4: 'Suivi des progrès',
    pFreeBtn: 'Démarrer gratuitement',
    pProBadge: 'Recommandé',
    pProTag: 'Professionnel',
    pProName: 'Pro',
    pProPeriod: 'par mois · 300 DT installation',
    pProAlts: 'ou 400 DT/trimestre · 1 400 DT/an',
    pPF1: 'Clients illimités',
    pPF2: 'Gestion complète des séances',
    pPF3: 'Tableau de bord analytique',
    pPF4: 'Profils coachs personnalisés',
    pPF5: 'Support prioritaire',
    pProBtn: 'Commencer',
    pEntTag: 'Entreprise',
    pEntName: 'Sur Mesure',
    pEntAmount: 'Devis',
    pEntPeriod: 'Adapté à vos besoins',
    pEF1: 'Multi-salles',
    pEF2: 'Intégrations personnalisées',
    pEF3: 'Gestionnaire de compte dédié',
    pEF4: 'Marque blanche disponible',
    pEntBtn: 'Nous contacter',
    footerSub: 'La plateforme de gestion pour les salles de sport tunisiennes',
    footerDemo: 'Réserver une démo',
    footerLogin: 'Connexion',
  },
  en: {
    navDemo: 'Book a Demo',
    navLogin: 'Login',
    heroBadge: '🇹🇳 Built for Tunisia',
    heroTitle: 'MANAGE\nYOUR GYM.\nEFFORTLESSLY.',
    heroSub: 'No more Excel sheets and WhatsApp groups. Trainw connects your coaches, clients and schedule in one place.',
    heroDemo: 'Book a Free Demo',
    heroLogin: 'Login',
    heroNote: '30-day free trial · No credit card required',
    hvSessions: 'Sessions Today',
    hvRevenue: 'Revenue',
    hvClients: 'Active Clients',
    hvDemoLabel: 'Example data',
    stat1: 'Booking Access',
    stat2: 'Roles in One · Gym · Coach · Client',
    stat3: 'Tunisia',
    whoTag: "Who it's for",
    whoTitle: 'Built for Everyone in the Gym',
    gymTitle: 'Gym Owners',
    gymDesc: 'Run your entire operation from one dashboard. Coaches, revenue, clients — all centralized.',
    gymB1: 'Real-time bookings & revenue',
    gymB2: 'Coach performance tracking',
    gymB3: 'Session and class scheduling',
    gymB4: 'Full member management',
    coachTitle: 'Coaches',
    coachDesc: 'Focus on training, not admin. Schedule, clients and earnings in one place.',
    coachB1: 'Centralized schedule & earnings',
    coachB2: 'Client progress tracking',
    coachB3: 'Session note generator',
    coachB4: 'Verified client reviews',
    clientTitle: 'Clients',
    clientDesc: 'Book sessions, track progress and stay connected with your coach — all in one place.',
    clientB1: 'Book sessions anytime',
    clientB2: 'Track measurements & weight',
    clientB3: 'Personalized nutrition guide',
    clientB4: 'Direct coach contact',
    whoCta: 'Get started →',
    howTag: 'How it works',
    howTitle: 'Up and Running in 3 Steps',
    how1Title: 'Create your gym',
    how1Desc: 'Sign up in 2 minutes. Add your gym name and info, and you\'re ready to go.',
    how2Title: 'Add coaches and clients',
    how2Desc: 'Invite your coaches, register your members. Each gets their own dashboard.',
    how3Title: 'Manage everything in one place',
    how3Desc: 'Schedule, bookings, client tracking, revenue — all centralized. No more WhatsApp chaos.',
    pricingTag: 'Pricing',
    pricingTitle: 'Simple and Transparent',
    pFreeTag: 'Free Trial',
    pFreeName: 'Starter',
    pFreePeriod: '30 days free',
    pFF1: 'Up to 50 clients',
    pFF2: 'Basic scheduling',
    pFF3: 'Client messaging',
    pFF4: 'Progress tracking',
    pFreeBtn: 'Start for free',
    pProBadge: 'Recommended',
    pProTag: 'Professional',
    pProName: 'Pro',
    pProPeriod: 'per month · 300 DT setup',
    pProAlts: 'or 400 DT/quarter · 1,400 DT/year',
    pPF1: 'Unlimited clients',
    pPF2: 'Full session management',
    pPF3: 'Analytics dashboard',
    pPF4: 'Personalized coach profiles',
    pPF5: 'Priority support',
    pProBtn: 'Get Started',
    pEntTag: 'Enterprise',
    pEntName: 'Custom',
    pEntAmount: 'Quote',
    pEntPeriod: 'Tailored to your needs',
    pEF1: 'Multi-location',
    pEF2: 'Custom integrations',
    pEF3: 'Dedicated account manager',
    pEF4: 'White-label available',
    pEntBtn: 'Contact us',
    footerSub: 'The gym management platform for Tunisia',
    footerDemo: 'Book a Demo',
    footerLogin: 'Login',
  },
  ar: {
    navDemo: 'احجز عرضاً',
    navLogin: 'تسجيل الدخول',
    heroBadge: '🇹🇳 مصمّم لتونس',
    heroTitle: 'أدِر\nصالتك.\nببساطة.',
    heroSub: 'انتهى وقت الإكسيل ومجموعات الواتساب. Trainw يجمع مدربيك وعملاءك وجدولك في مكان واحد.',
    heroDemo: 'احجز عرضاً مجانياً',
    heroLogin: 'تسجيل الدخول',
    heroNote: 'تجربة مجانية 30 يوماً · بدون بطاقة بنكية',
    hvSessions: 'جلسات اليوم',
    hvRevenue: 'الإيرادات',
    hvClients: 'العملاء النشطون',
    hvDemoLabel: 'بيانات توضيحية',
    stat1: 'حجز على مدار الساعة',
    stat2: 'ثلاثة أدوار في واحد',
    stat3: 'تونس',
    whoTag: 'لمن هو؟',
    whoTitle: 'مصمّم للجميع في الصالة',
    gymTitle: 'أصحاب الصالات',
    gymDesc: 'أدِر نشاطك كله من لوحة تحكم واحدة. المدربون والإيرادات والعملاء — كل شيء مركزي.',
    gymB1: 'الحجوزات والإيرادات في الوقت الفعلي',
    gymB2: 'متابعة أداء المدربين',
    gymB3: 'جدولة الجلسات والدروس',
    gymB4: 'إدارة شاملة للأعضاء',
    coachTitle: 'المدربون',
    coachDesc: 'ركّز على التدريب لا على الإدارة. الجدول والعملاء والأرباح في مكان واحد.',
    coachB1: 'جدول وأرباح مركزيان',
    coachB2: 'متابعة تقدم العملاء',
    coachB3: 'مولّد ملاحظات الجلسات',
    coachB4: 'تقييمات العملاء الموثّقة',
    clientTitle: 'العملاء',
    clientDesc: 'احجز جلساتك وتابع تقدمك وابقَ على تواصل مع مدربك — كل ذلك في مكان واحد.',
    clientB1: 'حجز الجلسات في أي وقت',
    clientB2: 'متابعة القياسات والوزن',
    clientB3: 'دليل تغذية شخصي',
    clientB4: 'تواصل مباشر مع المدرب',
    whoCta: 'ابدأ الآن →',
    howTag: 'كيف يعمل؟',
    howTitle: 'جاهز للعمل في 3 خطوات',
    how1Title: 'أنشئ صالتك',
    how1Desc: 'التسجيل في دقيقتين. أضف اسم صالتك ومعلوماتك وستكون جاهزاً.',
    how2Title: 'أضف مدربيك وعملاءك',
    how2Desc: 'ادعُ مدربيك وسجّل أعضاءك. كل واحد يحصل على لوحة تحكم خاصة به.',
    how3Title: 'أدِر كل شيء من مكان واحد',
    how3Desc: 'الجدول والحجوزات ومتابعة العملاء والإيرادات — كل شيء مركزي. وداعاً لفوضى الواتساب.',
    pricingTag: 'الأسعار',
    pricingTitle: 'بسيط وشفاف',
    pFreeTag: 'تجربة مجانية',
    pFreeName: 'البداية',
    pFreePeriod: '30 يوماً مجاناً',
    pFF1: 'حتى 50 عميلاً',
    pFF2: 'جدولة أساسية',
    pFF3: 'مراسلة العملاء',
    pFF4: 'متابعة التقدم',
    pFreeBtn: 'ابدأ مجاناً',
    pProBadge: 'موصى به',
    pProTag: 'الاحترافي',
    pProName: 'Pro',
    pProPeriod: 'شهرياً · 300 دت تركيب',
    pProAlts: 'أو 400 دت/ربع سنوي · 1,400 دت/سنوي',
    pPF1: 'عملاء غير محدودين',
    pPF2: 'إدارة جلسات كاملة',
    pPF3: 'لوحة تحليلات',
    pPF4: 'ملفات تعريف مخصصة للمدربين',
    pPF5: 'دعم ذو أولوية',
    pProBtn: 'ابدأ الآن',
    pEntTag: 'المؤسسات',
    pEntName: 'مخصص',
    pEntAmount: 'عرض سعر',
    pEntPeriod: 'مصمّم لاحتياجاتك',
    pEF1: 'دعم متعدد الصالات',
    pEF2: 'تكاملات مخصصة',
    pEF3: 'مدير حساب مخصص',
    pEF4: 'العلامة البيضاء متاحة',
    pEntBtn: 'تواصل معنا',
    footerSub: 'منصة إدارة الصالات الرياضية في تونس',
    footerDemo: 'احجز عرضاً',
    footerLogin: 'تسجيل الدخول',
  }
};

// Detect browser language, default FR for Tunisian users
function detectLang() {
  const saved = localStorage.getItem('trainw_lang');
  if (saved && T[saved]) return saved;
  const bl = navigator.language || navigator.userLanguage || 'fr';
  if (bl.startsWith('ar')) return 'ar';
  if (bl.startsWith('en')) return 'en';
  return 'fr';
}

let lang = detectLang();

function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (T[lang] && T[lang][key] !== undefined) el.textContent = T[lang][key];
  });
  // RTL for Arabic
  if (lang === 'ar') {
    document.documentElement.setAttribute('dir', 'rtl');
    document.documentElement.setAttribute('lang', 'ar');
  } else {
    document.documentElement.setAttribute('dir', 'ltr');
    document.documentElement.setAttribute('lang', lang);
  }
}

function setLang(l) {
  lang = l;
  localStorage.setItem('trainw_lang', l);
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.remove('active'));
  document.querySelector(`.lang-btn[data-lang="${l}"]`)?.classList.add('active');
  applyTranslations();
}

document.querySelectorAll('.lang-btn').forEach(btn => {
  btn.addEventListener('click', () => setLang(btn.dataset.lang));
});

// Set correct active button on load
document.querySelectorAll('.lang-btn').forEach(b => b.classList.remove('active'));
document.querySelector(`.lang-btn[data-lang="${lang}"]`)?.classList.add('active');

// Nav scroll effect
window.addEventListener('scroll', () => {
  document.getElementById('navbar').style.borderBottomColor =
    window.scrollY > 10 ? 'var(--bd)' : 'transparent';
});

applyTranslations();
